---
title: "Data_Analysis_Fieldwork"
author: "Aurora Mills"
date: "01.05.2023"
output: html_document
---

```{r, eval=FALSE}
install.packages("haven")
install.packages("dplyr")
install.packages("feather")
install.packages("cowplot")
install.packages("survey")
install.packages("car")
install.packages("gtsummary")
install.packages("MatchIt")
install.packages("mosaic")
```

```{r}
library(dplyr)
library(haven)
library(feather)
library(ggplot2)
library(table1) 
library(survey)
library(car)
library(gtsummary)
library(MatchIt)
library(tidyverse)
library(mosaic)
library(modelsummary)
```


```{r}
#SMART DATA 
smart<-read_xpt("MMSA2021_XPT.zip")
smart.variables <- dplyr::rename(smart, county= "MMSANAME", 
                                 county.weight= "_MMSAWT",
                                 state= "STATERE1", 
                                 education = "_EDUCAG", 
                                 sex = "_SEX", 
                                 income = "_INCOMG1", 
                                 race = "_MRACE1",
                                 age= "_AGE_G", 
                                 age65= "_AGE65YR", 
                                 BMI= "_BMI5CAT",
                                 SMOKERSTATUS = "_SMOKER3", 
                                 FORMERSMOKER = "_RFSMOK3", 
                                 ASTHMANOW= "_CASTHM1", 
                                 ASTHMA= "_ASTHMS1")
                              
#selected variables 
selected.smart<- (dplyr::select(smart.variables, county, county.weight, state, education, sex, income, race, age, age65, BMI, SMOKERSTATUS, FORMERSMOKER, ASTHMANOW, ASTHMA)) %>%

#Asthma Status
mutate(ASTHMANOW = ifelse(ASTHMANOW %in% c(7,9), NA, ifelse(ASTHMANOW == 2,0,1))) %>%
mutate(ASTHMANOW = factor(ASTHMANOW, levels = c(0,1), labels = c("No Asthma", "Asthma"))) %>%
filter(!is.na(ASTHMANOW))

#Sex
selected.smart$sex<- car::recode(selected.smart$sex, recodes = "1='Male'; 2='Female'")

#Race
selected.smart$race<- car::recode(selected.smart$race, recodes = "1= 'White'; 2= 'Black'; 3= 'AmericanIndian/AlaskanNative'; 4= 'Asian'; 5= 'NativeHawaiian/PacificIslander'; 6= 'Other'; 7= 'Multiracial'; 77:99= NA")

#Asthma Past 
selected.smart$ASTHMA<- car::recode(selected.smart$ASTHMA, recodes= "1= 'Asthma'; 2= 'FormerAsthma'; 3='NeverAsthma'; 9=NA")

#Income <35, 35-50k, 50-100k, >100k
selected.smart$income<- car::recode(selected.smart$income, recodes= "1:3= '<$35k'; 4= '$35-50k'; 5= '$50-100k'; 6:7= '>100k';9=NA")

#Smoker Status
selected.smart$SMOKERSTATUS<- car::recode(selected.smart$SMOKERSTATUS, recodes= "1:2='Current Smoker'; 3= 'Former Smoker'; 4= 'Never Smoker';9= NA")

#Age 18-24yr, 25-44yr, 45-64yr, >65
selected.smart$age<- car::recode(selected.smart$age, recodes = "1='18-24'; 2:3= '25-44'; 4:5= '45-64'; 6= '>65'")

#Age for Stratification 
selected.smart$age65<- car::recode(selected.smart$age65, recodes = "1= '0'; 2= '1'; 3= NA")

#Education 
selected.smart$education<- car::recode(selected.smart$education, recodes = "1= 'No HighSchool'; 2= 'HighSchool'; 3:4= 'Some/HigherEduca'; 9= NA")

#BMI
selected.smart$BMI<- car::recode(selected.smart$BMI, recodes= "1= 'Underweight'; 2='Normal'; 3:4='Overweight/Obese'; else= NA")


```

```{r}
#All NAs dropped
complete.smart<- tidyr::drop_na(selected.smart) 

complete.smart %>% gtsummary::tbl_summary()

```


```{r}
#Data Visualizations and Summary Tables 
selected.smart %>% gtsummary::tbl_summary()

selected.smart %>% 
  dplyr::select(-c(age65,FORMERSMOKER, state, county, county.weight)) %>%
  gtsummary::tbl_summary(by= ASTHMANOW)

ggplot(data=selected.smart, aes(x=ASTHMANOW))+
  geom_bar()

ggplot(data=selected.smart, aes(x=ASTHMA))+
  geom_bar()

ggplot(data = selected.smart, aes(x= race, fill= sex)) + 
  geom_bar(position = "dodge")  + 
  theme(axis.text.x = element_text(angle = 90))
```


```{r}
#Gets p-Value for Table1 
pvalue<- function(x, ...) {
  y<- unlist(x)
  g<- factor(rep(1:length(x), times=sapply(x, length)))
  if (is.numeric(y)) {
    p<- t.test(y~g)$p.value
  } else {
  p<- chisq.test(table(y,g))$p.value
  }
  c("", sub("<", "&lt;", format.pval(p, digits=3, eps=0.001)))
}


table1(~sex + race + education + income | ASTHMANOW, 
       data= selected.smart, overall =F, extra.col = list(`P-value`=pvalue))

table1(~county | ASTHMANOW, 
       data= selected.smart, overall =F, extra.col = list(`P-value`=pvalue))

#Potential confounding 
table1(~factor(age65) + SMOKERSTATUS + BMI | ASTHMANOW, 
       data= selected.smart, overall =F, extra.col = list(`P-value`=pvalue))

```

```{r}
#Logisitic Regression Models. (Only outcome needs to be binary)
tally(~ ASTHMANOW | age65, margins=TRUE, data= selected.smart)

ggplot(data = selected.smart, aes(x = factor(ASTHMANOW), fill = sex))+
  geom_bar(position = "fill")

ggplot(data = selected.smart, aes(x = factor(ASTHMANOW), fill= race)) + 
  geom_bar(position = "fill")

chisq.test(table(selected.smart$ASTHMANOW, selected.smart$sex))

summary((glm(ASTHMANOW ~ sex, data = selected.smart, family = binomial())))

exp(coef(glm(ASTHMANOW ~ sex, data = selected.smart, family = binomial()))) #odds ratio

chisq.test(table(selected.smart$ASTHMANOW, selected.smart$race))

summary((glm(ASTHMANOW ~ race, data = selected.smart, family = binomial())))

#Combined models
asthma.fit<- glm(ASTHMANOW ~ race + age65 + sex, data = selected.smart, family = binomial())
summary(asthma.fit)
exp(coef(asthma.fit)) #odds ratio

asthma.fit2<- glm(ASTHMANOW ~ BMI + FORMERSMOKER + age65, data = selected.smart, family = binomial())
summary(asthma.fit2)

```


```{r}
#Census Data and MMSA
```

